title: "Perfiz"

remote_theme: pmarsceill/just-the-docs
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/znsio/perfiz" # the github URL for your repo
gh_edit_branch: "gh-pages"

heading_anchors: true

aux_links:
  "Perfiz on GitHub":
    - "//github.com/znsio/perfiz"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

aux_links_new_tab: false

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Distributed by an <a href=\"https://github.com/znsio/perfiz/tree/master/LICENSE.md\">MIT license.</a>"

# logo: "/images/perfiz-logo.png"
