version: '3.8'
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    links:
      - prometheus:prometheus
    volumes:
      - ${PROJECT_DIR}/perfiz/grafana_data:/var/lib/grafana
      - ${PROJECT_DIR}/perfiz/dashboards:/var/lib/grafana/dashboards
      - ./prometheus-metrics-monitor/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - perfiz-network
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ${PROJECT_DIR}/perfiz/prometheus/:/etc/prometheus/
      - ${PROJECT_DIR}/perfiz/prometheus_data:/prometheus
    depends_on:
      - cadvisor
    networks:
      - perfiz-network
  cadvisor:
    image: "google/cadvisor"
    container_name: cadvisor
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw # This works on Mac
#      - /var/run:/var/run:ro # This may work on Linux
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - perfiz-network
  influxgraph:
    environment:
      INFLUXGRAPH_GUNICORN_LOGLEVEL: "debug"
      INFLUXGRAPH_GUNICORN_TIMEOUT: "300"
      INFLUXGRAPH_GUNICORN_WORKERS: "2"
    image: "influxgraph/influxgraph"
    links:
      - influxdb:influxdb
    ports:
      - "8000:80"
    networks:
      - perfiz-network
  influxdb:
    environment:
      INFLUXDB_REPORTING_DISABLED: "true"
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_GRAPHITE_TEMPLATES: "measurement.field*"
      INFLUXDB_GRAPHITE_DATABASE: "telegraf"
    image: "influxdb:1.8.5"
    ports:
      - "8086:8086"
      - "2003:2003"
    volumes:
      - ${PROJECT_DIR}/perfiz/influxdb_data:/var/lib/influxdb
    networks:
      - perfiz-network

networks:
  perfiz-network:
    name: "perfiz-network"
