name: GenerateZip
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Write Version
        run: git describe > .VERSION
      - name: Zip Folder
        run: zip -r perfiz.zip . -x *.git*
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "perfiz.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
